<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Blog
 */
?>
<div class="search-query fix-me">
    <form id="mp_blog_content_search " action="<?= $block->escapeUrl($block->getSearchUrl()); ?>" method="get">
        <div class="input-box">
            <input
                type="text"
                placeholder="<?= $block->escapeHtml($block->getBlockHeader()); ?>"
                class="input-text required-entry placeholder"
                title="<?= $block->escapeHtml($block->getBlockHeader()); ?>"
                id="search-blog" name="query"
                value="<?= $block->escapeHtml($block->getQuery()); ?>"
                maxlength="100" />

            <button class="button" title="<?= $block->escapeHtml(__("Search")); ?>" type="submit">
                <i class="glyphicons search <?= $block->escapeHtml($block->getColorClass()); ?>"></i>
            </button>
        </div>
    </form>
</div>
