<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Blog
 */
?>
<?php
/** @var \Amasty\Blog\Block\Layout $block */
?>

<div class="amblog-blog-wrap mobile <?= /* @noEscape */ $block->getMobileLayoutCode(); ?>">
    <?php foreach ($block->getMobileBlocks('content') as $alias) : ?>
        <?= /* @noEscape */ $block->getContentBlockHtml($alias); ?>
    <?php endforeach; ?>
</div>
