<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Blog
 */
?>
<?php
/** @var \Amasty\Blog\Block\Content\Post\Details $block */

$tags = $block->getTags(); ?>

<?php if ($tags && count($tags)) : ?>
    <?php $isFirst = true; ?>
    <?php foreach ($tags as $tag) : ?>
        <?php if (!$isFirst) : ?>
            ,
        <?php endif ?>
        <a href="<?= $block->escapeUrl($tag->getTagUrl()); ?>" class="amblog-tag">
            #<?= $block->escapeHtml($tag->getName()); ?>
        </a>
        <?php $isFirst = false; ?>
    <?php endforeach; ?>
<?php endif; ?>
