<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Blog
 */
?>
<?php

/** @var \Amasty\Blog\Block\Content\Post\Details $block */

$post = $block->getPost();
?>
<?php if ($block->showAuthor() && $post->getPostedBy()) : ?>
    <div class="amblog-wrap">
        <svg class="amblog-svg user <?= $block->escapeHtml($block->getColorClass()); ?>">
            <use xlink:href="<?= $block->escapeUrl($block->getViewFileUrl('Amasty_Blog::images/sprite.svg')); ?>#user"></use>
        </svg>
        <div class="amblog-item -author">
        <?= $block->escapeHtml(__("By ")); ?>
            <?php if ($block->useSocialProfile()) : ?>
            <a rel="author"
               class="amblog-ref"
               href="<?= $block->escapeUrl($block->getSocialProfileUrl()); ?>"
               target="_blank"
               title="<?= $block->escapeHtml($post->getPostedBy()); ?>">
            <?php endif; ?>
            <?= $block->escapeHtml($post->getPostedBy()); ?>
        <?php if ($block->useSocialProfile()) : ?>
            </a>
        <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
