<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Blog
 */
?>
<?php
/** @var \Amasty\Blog\Block\Sidebar\Category $block */

$treeHtml = $block->renderCategoriesTreeHtml();
?>

<?php if ($block->getDisplay() && $treeHtml) : ?>
    <div class="amblog-categories sidebar-item">
        <div class="amblog-amp-title">
            <?= $block->escapeHtml($block->getBlockHeader()); ?>
        </div>
        <ul class="categories item level-<?= /* @noEscape */ $block->getDefaultLevel(); ?>">
            <?= /* @noEscape */ $treeHtml; ?>
        </ul>
    </div>
<?php endif; ?>
