<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Blog
 */
?>
<?php
/** @var \Amasty\Blog\Block\Sidebar\Recentpost $block */

$collection = $block->getCollection();
?>

<?php if ($block->getDisplay() && count($collection)) : ?>
    <div class="amblog-recentposts sidebar-item">
    <div class="amblog-amp-title">
        <?= $block->escapeHtml($block->getBlockHeader()); ?>
    </div>
    <?php foreach ($collection as $post) : ?>
        <?php $activeClass = $post->getIsActive() ? '-active' : ''; ?>
        <div class="item amblog-recent-post <?= /* @noEscape */ $activeClass ?>">
            <?php if ($block->hasThumbnail($post) && $block->showImages()) : ?>
                <div class="amp-img-container">
                    <a href="<?= $block->escapeUrl($post->getPostUrl()); ?>"
                       title="<?= $block->escapeHtml($post->getTitle()); ?>">
                        <amp-img alt="<?= $block->escapeHtml($post->getThumbnailAlt()); ?>"
                                 src="<?= $block->escapeUrl($block->getThumbnailSrc($post)); ?>"
                                 layout="fill">
                        </amp-img>
                    </a>
                </div>
            <?php endif; ?>
            <a href="<?= $block->escapeUrl($post->getPostUrl()); ?>">
                <?= $block->escapeHtml($post->getTitle()); ?>
            </a>
            <?php if ($block->needShowDate()) : ?>
                <div class="am-sidebar-date">
                    <?= /* @noEscape */ $block->renderDate($post->getCreatedAt()); ?>
                </div>
            <?php endif; ?>
            <?php if ($block->needShowThesis()) : ?>
                <div class="am-post-thesis">
                    <?= /* @noEscape */ $block->getStrippedContent($post->getShortContent()); ?>
                </div>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
    </div>
<?php endif; ?>
