<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Checkout
 */
?>
<?php /** @var \Amasty\Checkout\Block\Onepage\Head $block */ ?>

<style>
    <?php foreach ($block->getFields() as $code => $width) : ?>
    .fieldset.address [name$=".<?= $block->escapeHtml($code) ?>"] {
        width: <?= $block->escapeHtml($width) ?>%;
    }
    <?php endforeach; ?>
    
    <?php if ($font = $block->getCustomFont()) : ?>
    body {
        font-family: '<?= $block->escapeHtml($font) ?>',
        'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif !important;
    }
    <?php endif ?>
    
    <?php if ($color = $block->getHeadingTextColor()) : ?>
    .step-title,
    .amcheckout-step-container .amcheckout-title {
        color: <?= $block->escapeHtml($color) ?> !important;
    }
    <?php endif ?>

    <?php if ($color = $block->getBackgroundColor()) : ?>
    #checkout {
        background: <?= $block->escapeHtml($color) ?> !important;
    }
    .am-submit-fixed #checkout-payment-method-load .actions-toolbar {
        background: <?= $block->escapeHtml($color) ?> !important;
    }

    <?php endif ?>

    <?php if ($color = $block->getSummaryBackgroundColor()) : ?>
    .opc-block-summary {
        background-color: <?= $block->escapeHtml($color) ?> !important;
    }
    <?php endif ?>

    <?php if ($color = $block->getButtonColor()) : ?>
    .primary .action.checkout,
    .action.checkout.amasty {
        background-color: <?= $block->escapeHtml($color['normal']) ?> !important;
        border: none !important;
    }
    .primary .action.checkout:hover,
    .action.checkout.amasty:hover {
        background-color: <?= $block->escapeHtml($color['hover']) ?> !important;
        border: none !important;
    }
    <?php endif ?>
</style>
