<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<a class="link-copyright-t2n" href="mailto:thanhext@gmail.com" target="_blank" title="<?= /* @escapeNotVerified */ __('t2n') ?>"><img src="<?php echo $this->getViewFileUrl('T2N_AdminLogo::images/logo.svg'); ?>" height="16" width="16" /></a>
<?= /* @escapeNotVerified */ __('Power by ') ?><a href="mailto:thanhext@gmail.com">Thomas Nguyen</a><?= /* @escapeNotVerified */ __('. All rights reserved.') ?>
